# Outdoor temperature sensor configuration

# Broadcast provider configuration
substitutions:
  temperature_provider_node_name: ets1

udp:
  providers:
    - name: $temperature_provider_node_name
      encryption: !secret broadcast_key

# Sensor configurations
sensor:
  # Active outdoor temperature sensor (automatic fail-over with backup value)
  - platform: template
    name: $node_prefix utetemperatur
    id: outdoor_temperature
    icon: mdi:thermometer
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    update_interval: 20s
    lambda: |-
      if ( !isnan(id(outdoor_temperature_remote).state) )
        return id(outdoor_temperature_remote).state;
      if ( !isnan(id(outdoor_temperature_broadcast).state) )
        return id(outdoor_temperature_broadcast).state;
      return 10.0;

  # Remote outdoor temperature sensor (Home Assistant)
  - platform: homeassistant
    id: outdoor_temperature_remote
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    entity_id: sensor.utetemperatur
    filters:
      - heartbeat: 20s

  # Remote outdoor temperature sensor (Broadcast)
  - platform: udp
    provider: $temperature_provider_node_name
    id: outdoor_temperature_broadcast
    unit_of_measurement: °C
    device_class: temperature
    state_class: measurement
    accuracy_decimals: 2
    remote_id: outdoor_temperature
