# Status configuration

# Controller status indicator
output:
  - platform: esp8266_pwm
    id: ${node_name}_controller_status
    pin: GPIO14

# System status indicator
light:
  # LED on during normal operation; set inverted to true
  - platform: status_led
    name: $node_prefix systemstatus
    id: ${node_name}_system_status_indicator
    pin:
      number: GPIO13
      inverted: false
  # LED on during normal operation; set inverted to false
  - platform: status_led
    id: system_status_led
    pin:
      number: GPIO02
      inverted: false
# Controller status indicator
  - platform: monochromatic
    name: $node_prefix reglerstatus
    id: ${node_name}_controller_status_indicator
    output: ${node_name}_controller_status
    effects:
      - pulse:
          name: auto_mode
          transition_length: 0.2s
          update_interval: 0.6s
      - pulse:
          name: manual_mode
          transition_length: 0.2s
          update_interval: 2s

# Controller operational state indication
binary_sensor:
  - platform: homeassistant
    id: zone_actuator_status
    entity_id: binary_sensor.${zone_id}_aktiv
    publish_initial_state: true
    on_press:
      - light.turn_on:
          id: ${node_name}_controller_status_indicator
          effect: none
    on_release:
      - light.turn_off:
          id: ${node_name}_controller_status_indicator
